version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "pyformlang"
        versions:
          - ">=1.0.0"
