language: python
cache: pip
jobs:
  include:
    - name: "Docker"
      services:
        - docker
      python: "3.8.0"
      script:
        - docker build -t cfpq_data .
        - docker run -it --rm -v "$PWD":/CFPQ_Data cfpq_data python3 -m pytest --doctest-modules -vv -s
    - name: "Linux"
      os: linux
      python: "3.8.0"
    - name: "MacOS"
      os: osx
      osx_image: xcode12u
      language: shell
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script: PYTHONPATH=. pytest --doctest-modules -vv -s
