"""Strip stored reverse edges from a graph archive.

Per the archive conventions (see the "Reversed edges" section of the graphs
page) reversed edges are never stored: for a label ``L`` the reverse ``L_r`` is
auto-generated by :func:`flpq_data.graphs.utils.add_reverse_edges`. Some legacy
archives still bundle reverse matrices — the unindexed ``L_r.mtx`` or the
indexed ``<base>_r_<n>.mtx`` — which
:func:`check_archive_structure.stored_reverse_forward` flags.

This tool removes those matrices, updates the archive ``README.md`` ("Edges and
labels": the reverse bullet lines are dropped and the stored-edge total is
recomputed), and re-validates the result. The precomputed ``results.mtx`` are
untouched: reachability does not depend on the redundant reverse matrices.

Usage (from any directory)::

    python utils/strip_reverse_edges.py ARCHIVE.tar.gz -o STRIPPED.tar.gz

``ARCHIVE`` may also be an unpacked directory. The output must be named after
the graph (``<graph>.tar.gz``) — the upload tool stores it under that name.
"""

import argparse
import pathlib
import re
import shutil
import tarfile
import tempfile
from dataclasses import dataclass, field
from typing import Optional, Sequence, Set, Union

from check_archive_structure import (
    stored_reverse_forward,
    unpack_single_dir,
    validate_archive,
)

__all__ = ["StripReport", "strip_reverse_edges", "main"]

#: A README "Edges and labels" bullet, e.g.
#: ``- `load_r_<i>` (i = 0..393, 380 labels): 1578 edges``.
_BULLET_RE = re.compile(
    r"^(?P<indent>\s*)-\s+`(?P<label>[^`]+)`.*?:\s*(?P<count>\d+)\s+edges\s*$"
)
#: The stored-edge total line, e.g. ``19843 stored edges:``.
_TOTAL_RE = re.compile(r"^(?P<indent>\s*)\d+ stored edges:\s*$")
#: An index placeholder at the end of a README label (``load_r_<i>`` -> ``load_r``).
_PLACEHOLDER_RE = re.compile(r"_<[a-z]+>$")
#: A concrete index at the end of a matrix stem (``load_r_5`` -> ``load_r``).
_STEM_INDEX_RE = re.compile(r"_\d+$")


@dataclass
class StripReport:
    """The outcome of a strip run.

    Attributes
    ----------
    problems : list[str]
        All problems found; empty when the stripped archive was written.
    removed : list[str]
        The stems of the reverse matrices removed.
    total_before, total_after : int
        The README stored-edge total before and after stripping (0 when the
        archive has no parsable total).
    """

    problems: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    total_before: int = 0
    total_after: int = 0


def _readme_family(label: str) -> str:
    """The matrix family of a README edge label (drop the index placeholder).

    Examples
    --------
    >>> _readme_family("load_r_<i>")
    'load_r'
    >>> _readme_family("alloc_r")
    'alloc_r'
    """
    return _PLACEHOLDER_RE.sub("", label)


def _stem_family(stem: str) -> str:
    """The matrix family of a file stem (drop the concrete index).

    Examples
    --------
    >>> _stem_family("load_r_5")
    'load_r'
    >>> _stem_family("alloc_r")
    'alloc_r'
    """
    return _STEM_INDEX_RE.sub("", stem)


def _strip_readme(text: str, removed_families: Set[str]) -> tuple[str, int, int]:
    """Remove reverse bullets and recompute the stored-edge total.

    Returns the new text, the total before, and the total after (the totals
    are 0 when the "Edges and labels" section or its total line is missing).
    """
    lines = text.splitlines()
    start = next(
        (i for i, line in enumerate(lines) if line.strip() == "## Edges and labels"),
        None,
    )
    if start is None:
        return text, 0, 0
    end = start + 1
    while end < len(lines) and not lines[end].startswith("## "):
        end += 1

    kept = lines[: start + 1]
    total_before = 0
    total_after = 0
    total_line = None
    total_indent = ""
    for line in lines[start + 1 : end]:
        total_match = _TOTAL_RE.match(line)
        if total_match is not None:
            total_before = int(line.split()[0])
            total_line = len(kept)
            total_indent = total_match.group("indent")
            kept.append(line)
            continue
        bullet = _BULLET_RE.match(line)
        if bullet is not None:
            count = int(bullet.group("count"))
            if _readme_family(bullet.group("label")) in removed_families:
                continue
            total_after += count
            kept.append(line)
        else:
            kept.append(line)
    if total_line is not None:
        kept[total_line] = f"{total_indent}{total_after} stored edges:"
    kept.extend(lines[end:])
    return (
        "\n".join(kept) + ("\n" if text.endswith("\n") else ""),
        total_before,
        total_after,
    )


def strip_reverse_edges(
    source: Union[str, pathlib.Path],
    output: Union[str, pathlib.Path],
) -> StripReport:
    """Write ``source`` with every stored reverse matrix removed.

    Parameters
    ----------
    source : Union[str, Path]
        The archive to strip: a ``.tar.gz`` or an unpacked directory.
    output : Union[str, Path]
        Where to write the stripped ``.tar.gz`` (named after the graph).

    Returns
    -------
    report : StripReport
        The removed matrices, the README totals, and any problems. The output
        is written only when ``report.problems`` is empty.
    """
    output = pathlib.Path(output)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = pathlib.Path(tmp)
        source_path = pathlib.Path(source)
        try:
            if source_path.is_dir():
                root = tmp_path / "source" / source_path.name
                shutil.copytree(source_path, root)
            else:
                root = unpack_single_dir(source_path, tmp_path / "source")
        except (ValueError, OSError, tarfile.TarError) as error:
            return StripReport(problems=[str(error)])

        graph_dir = root / "graph"
        if not graph_dir.is_dir():
            return StripReport(problems=["archive has no graph/ directory"])

        stems = {path.stem for path in graph_dir.glob("*.mtx")}
        removed = sorted(
            stem for stem in stems if stored_reverse_forward(stem, stems) is not None
        )
        report = StripReport(removed=removed)
        removed_families = {_stem_family(stem) for stem in removed}

        for stem in removed:
            (graph_dir / f"{stem}.mtx").unlink()

        readme = root / "README.md"
        if removed_families and readme.is_file():
            text = readme.read_text(encoding="utf-8")
            stripped, report.total_before, report.total_after = _strip_readme(
                text, removed_families
            )
            readme.write_text(stripped, encoding="utf-8")

        problems = validate_archive(root)
        if problems:
            report.problems = problems
            return report

        if output.name != f"{root.name}.tar.gz":
            report.problems = [
                f"the output file must be named {root.name}.tar.gz "
                f"(the upload tool stores it under that name), got {output.name!r}"
            ]
            return report
        with tarfile.open(output, "w:gz") as tarball:
            tarball.add(root, arcname=root.name)
        return report


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Command-line entry point.

    Returns
    -------
    status : int
        0 when the stripped archive was written, 1 otherwise.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Strip stored reverse matrices from a graph archive and recompute "
            "the README stored-edge total."
        )
    )
    parser.add_argument(
        "source",
        help="the archive to strip (.tar.gz or unpacked directory)",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="where to write the stripped .tar.gz (named after the graph)",
    )
    args = parser.parse_args(argv)

    report = strip_reverse_edges(args.source, args.output)
    if report.problems:
        for problem in report.problems:
            print(f"error: {problem}")
        print(f"{len(report.problems)} problem(s) found; nothing was written")
        return 1
    print(
        f"removed {len(report.removed)} reverse matrix file(s); "
        f"README total {report.total_before} -> {report.total_after}; "
        f"wrote {args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
