name: Deploy docs

on:
  push:
    branches: [ master ]

jobs:
  documentation:
    # Do not attempt to deploy documentation on forks
    if: github.repository_owner == 'FormalLanguageConstrainedPathQuerying'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -r requirements/docs.txt
          python -m pip install .
          python -m pip list

      - name: Build
        run: make -C docs/ html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
