name: ci docker

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, macos-10.15, macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: cfpq_data:latest

      - name: Run tests inside Docker
        uses: addnab/docker-run-action@v3
        with:
          image: cfpq_data:latest
          run: python3 -m pytest --doctest-modules -vv -s
