name: Code style check

on: [ push, pull_request ]

jobs:
  style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pre-commit
        run: |
          python -m pip install pre-commit==3.6.2
          pre-commit install

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --color always --verbose --show-diff-on-failure
