name: Continuous integration

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-18.04,
            ubuntu-20.04,
            ubuntu-latest,
            macos-10.15,
            macos-latest,
            windows-2016,
            windows-2019,
            windows-latest,
        ]
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install .
          python -m pip list

      - name: Test CFPQ_Data
        run: |
          pytest --doctest-modules -vv -s cfpq_data tests

  # Only supported on linux platform
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-18.04,
            ubuntu-20.04,
            ubuntu-latest,
        ]
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: cfpq_data:latest

      - name: Run tests inside Docker
        uses: addnab/docker-run-action@v3
        with:
          image: cfpq_data:latest
          run: python3 -m pytest --doctest-modules -vv -s cfpq_data tests
