name: Continuous integration

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            ubuntu-latest,
            macos-latest,
            windows-latest,
        ]
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -r requirements/tests.txt
          python -m pip install .
          python -m pip list

      - name: Test CFPQ_Data
        run: |
          pytest --doctest-modules -vv -s cfpq_data tests
